# Generated by Django 3.1.2 on 2020-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201107_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptrent',
            name='built_year',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='aptrent',
            name='deposit',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='aptrent',
            name='floor',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='aptrent',
            name='rent_price',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='aptrent',
            name='size',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='apttrade',
            name='built_year',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='apttrade',
            name='floor',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='apttrade',
            name='price',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='apttrade',
            name='size',
            field=models.CharField(max_length=12),
        ),
    ]
